FROM python:3.14-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn","main:app", "--host","0.0.0.0","--port","8000"]

# API_URL = "http://cancer-backend:8000/predict" # change if backend is hosted elsewhere

# model = mlflow.pyfunc.load_model(
#     "mlruns/2/models/m-e2558af1e89c47d99ecb88d161cae3a6/artifacts"
# )